// Code generated by MockGen. DO NOT EDIT.
// Source: hero.go

// Package mock_hero is a generated GoMock package.
package mock_hero

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHero is a mock of Hero interface
type MockHero struct {
	ctrl     *gomock.Controller
	recorder *MockHeroMockRecorder
}

// MockHeroMockRecorder is the mock recorder for MockHero
type MockHeroMockRecorder struct {
	mock *MockHero
}

// NewMockHero creates a new mock instance
func NewMockHero(ctrl *gomock.Controller) *MockHero {
	mock := &MockHero{ctrl: ctrl}
	mock.recorder = &MockHeroMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHero) EXPECT() *MockHeroMockRecorder {
	return m.recorder
}

// GetName mocks base method
func (m *MockHero) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockHeroMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockHero)(nil).GetName))
}

// GetWeapon mocks base method
func (m *MockHero) GetWeapon() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeapon")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWeapon indicates an expected call of GetWeapon
func (mr *MockHeroMockRecorder) GetWeapon() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeapon", reflect.TypeOf((*MockHero)(nil).GetWeapon))
}
